// Test bench generated by generator_verilog.py

`timescale 1ns / 1ps

module testfixture();

reg clk;
reg reset;

initial begin
  reset = 1'b1;
  clk   = 1'b1;
end

initial begin
  #1080
  reset = 1'b0;
end

reg en_proc = 1'b0;
always @(posedge clk) begin
  if (reset) en_proc = 1'b0;
  else       en_proc = 1'b1;
end

always begin
  #2.5 clk = ~clk;
end

reg[2:0] bx_in_ProjectionRouter;
initial bx_in_ProjectionRouter = 3'b110;
always begin
 #540 bx_in_ProjectionRouter <= bx_in_ProjectionRouter + 1'b1;
end
wire[2:0] bx_out_MatchCalculator;
   
wire   MatchCalculator_done;
   
//
// All Stubs
//
reg AS_L3PHICn4_dataarray_data_V_wea;
wire[9:0] AS_L3PHICn4_dataarray_data_V_writeaddr;
wire[35:0] AS_L3PHICn4_dataarray_data_V_din;
reg AS_L3PHICn4_nentries_0_V_we;
wire[7:0] AS_L3PHICn4_nentries_0_V_din;
reg AS_L3PHICn4_nentries_1_V_we;
wire[7:0] AS_L3PHICn4_nentries_1_V_din;
reg AS_L3PHICn4_nentries_2_V_we;
wire[7:0] AS_L3PHICn4_nentries_2_V_din;
reg AS_L3PHICn4_nentries_3_V_we;
wire[7:0] AS_L3PHICn4_nentries_3_V_din;
reg AS_L3PHICn4_nentries_4_V_we;
wire[7:0] AS_L3PHICn4_nentries_4_V_din;
reg AS_L3PHICn4_nentries_5_V_we;
wire[7:0] AS_L3PHICn4_nentries_5_V_din;
reg AS_L3PHICn4_nentries_6_V_we;
wire[7:0] AS_L3PHICn4_nentries_6_V_din;
reg AS_L3PHICn4_nentries_7_V_we;
wire[7:0] AS_L3PHICn4_nentries_7_V_din;
wire AS_L3PHICn4_dataarray_data_V_enb;
wire[9:0] AS_L3PHICn4_dataarray_data_V_readaddr;
wire[35:0] AS_L3PHICn4_dataarray_data_V_dout;
wire[7:0] AS_L3PHICn4_nentries_0_V_dout;
wire[7:0] AS_L3PHICn4_nentries_1_V_dout;
wire[7:0] AS_L3PHICn4_nentries_2_V_dout;
wire[7:0] AS_L3PHICn4_nentries_3_V_dout;
wire[7:0] AS_L3PHICn4_nentries_4_V_dout;
wire[7:0] AS_L3PHICn4_nentries_5_V_dout;
wire[7:0] AS_L3PHICn4_nentries_6_V_dout;
wire[7:0] AS_L3PHICn4_nentries_7_V_dout;

initial begin
  AS_L3PHICn4_nentries_0_V_we = 1'b1;
  AS_L3PHICn4_nentries_1_V_we = 1'b1;
  AS_L3PHICn4_nentries_2_V_we = 1'b1;
  AS_L3PHICn4_nentries_3_V_we = 1'b1;
  AS_L3PHICn4_nentries_4_V_we = 1'b1;
  AS_L3PHICn4_nentries_5_V_we = 1'b1;
  AS_L3PHICn4_nentries_6_V_we = 1'b1;
  AS_L3PHICn4_nentries_7_V_we = 1'b1;
end

reg[7:0] AS_L3PHICn4_nentreg_0 = 8'b00111110; // FIX
reg[7:0] AS_L3PHICn4_nentreg_1 = 8'b00111010; // FIX
reg[7:0] AS_L3PHICn4_nentreg_2 = 8'b00000000; // FIX
reg[7:0] AS_L3PHICn4_nentreg_3 = 8'b00000000; // FIX
reg[7:0] AS_L3PHICn4_nentreg_4 = 8'b00000000; // FIX
reg[7:0] AS_L3PHICn4_nentreg_5 = 8'b00000000; // FIX
reg[7:0] AS_L3PHICn4_nentreg_6 = 8'b00000000; // FIX
reg[7:0] AS_L3PHICn4_nentreg_7 = 8'b00000000; // FIX
assign AS_L3PHICn4_nentries_0_V_din = AS_L3PHICn4_nentreg_0;
assign AS_L3PHICn4_nentries_1_V_din = AS_L3PHICn4_nentreg_1;
assign AS_L3PHICn4_nentries_2_V_din = AS_L3PHICn4_nentreg_2;
assign AS_L3PHICn4_nentries_3_V_din = AS_L3PHICn4_nentreg_3;
assign AS_L3PHICn4_nentries_4_V_din = AS_L3PHICn4_nentreg_4;
assign AS_L3PHICn4_nentries_5_V_din = AS_L3PHICn4_nentreg_5;
assign AS_L3PHICn4_nentries_6_V_din = AS_L3PHICn4_nentreg_6;
assign AS_L3PHICn4_nentries_7_V_din = AS_L3PHICn4_nentreg_7;

Memory #(
  .RAM_WIDTH(36),
  .RAM_DEPTH(1024),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("AS_L3PHICn4.dat")
) AS_L3PHICn4 (
  .clka(clk),
  .clkb(clk),
  .wea(AS_L3PHICn4_dataarray_data_V_wea),
  .addra(AS_L3PHICn4_dataarray_data_V_writeaddr),
  .dina(AS_L3PHICn4_dataarray_data_V_din),
  .nent_we0(AS_L3PHICn4_nentries_0_V_we),
  .nent_i0(AS_L3PHICn4_nentries_0_V_din),
  .nent_we1(AS_L3PHICn4_nentries_1_V_we),
  .nent_i1(AS_L3PHICn4_nentries_1_V_din),
  .nent_we2(AS_L3PHICn4_nentries_2_V_we),
  .nent_i2(AS_L3PHICn4_nentries_2_V_din),
  .nent_we3(AS_L3PHICn4_nentries_3_V_we),
  .nent_i3(AS_L3PHICn4_nentries_3_V_din),
  .nent_we4(AS_L3PHICn4_nentries_4_V_we),
  .nent_i4(AS_L3PHICn4_nentries_4_V_din),
  .nent_we5(AS_L3PHICn4_nentries_5_V_we),
  .nent_i5(AS_L3PHICn4_nentries_5_V_din),
  .nent_we6(AS_L3PHICn4_nentries_6_V_we),
  .nent_i6(AS_L3PHICn4_nentries_6_V_din),
  .nent_we7(AS_L3PHICn4_nentries_7_V_we),
  .nent_i7(AS_L3PHICn4_nentries_7_V_din),
  .enb(AS_L3PHICn4_dataarray_data_V_enb),
  .addrb(AS_L3PHICn4_dataarray_data_V_readaddr),
  .doutb(AS_L3PHICn4_dataarray_data_V_dout),
  .nent_o0(AS_L3PHICn4_nentries_0_V_dout),
  .nent_o1(AS_L3PHICn4_nentries_1_V_dout),
  .nent_o2(AS_L3PHICn4_nentries_2_V_dout),
  .nent_o3(AS_L3PHICn4_nentries_3_V_dout),
  .nent_o4(AS_L3PHICn4_nentries_4_V_dout),
  .nent_o5(AS_L3PHICn4_nentries_5_V_dout),
  .nent_o6(AS_L3PHICn4_nentries_6_V_dout),
  .nent_o7(AS_L3PHICn4_nentries_7_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_din;
reg TPROJ_L1L2XXH_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_0_V_din;
reg TPROJ_L1L2XXH_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXH_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L1L2XXH_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L1L2XXH_L3PHIC_nentreg_0 = 8'b00000110; // 6
reg[7:0] TPROJ_L1L2XXH_L3PHIC_nentreg_1 = 8'b00001000; // 8
assign TPROJ_L1L2XXH_L3PHIC_nentries_0_V_din = TPROJ_L1L2XXH_L3PHIC_nentreg_0;
assign TPROJ_L1L2XXH_L3PHIC_nentries_1_V_din = TPROJ_L1L2XXH_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L1L2H_L3PHIC_04MOD.dat")
) TPROJ_L1L2XXH_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_din;
reg TPROJ_L5L6XXC_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_0_V_din;
reg TPROJ_L5L6XXC_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L5L6XXC_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L5L6XXC_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L5L6XXC_L3PHIC_nentreg_0 = 8'b00001010; // 10
reg[7:0] TPROJ_L5L6XXC_L3PHIC_nentreg_1 = 8'b00000010; // 2
assign TPROJ_L5L6XXC_L3PHIC_nentries_0_V_din = TPROJ_L5L6XXC_L3PHIC_nentreg_0;
assign TPROJ_L5L6XXC_L3PHIC_nentries_1_V_din = TPROJ_L5L6XXC_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L5L6C_L3PHIC_04MOD.dat")
) TPROJ_L5L6XXC_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_din;
reg TPROJ_L1L2XXI_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_0_V_din;
reg TPROJ_L1L2XXI_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXI_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L1L2XXI_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L1L2XXI_L3PHIC_nentreg_0 = 8'b00001010; // 10
reg[7:0] TPROJ_L1L2XXI_L3PHIC_nentreg_1 = 8'b00001011; // 11
assign TPROJ_L1L2XXI_L3PHIC_nentries_0_V_din = TPROJ_L1L2XXI_L3PHIC_nentreg_0;
assign TPROJ_L1L2XXI_L3PHIC_nentries_1_V_din = TPROJ_L1L2XXI_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L1L2I_L3PHIC_04MOD.dat")
) TPROJ_L1L2XXI_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_din;
reg TPROJ_L5L6XXB_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_0_V_din;
reg TPROJ_L5L6XXB_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L5L6XXB_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L5L6XXB_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L5L6XXB_L3PHIC_nentreg_0 = 8'b00000000; // 0
reg[7:0] TPROJ_L5L6XXB_L3PHIC_nentreg_1 = 8'b00000000; // 0
assign TPROJ_L5L6XXB_L3PHIC_nentries_0_V_din = TPROJ_L5L6XXB_L3PHIC_nentreg_0;
assign TPROJ_L5L6XXB_L3PHIC_nentries_1_V_din = TPROJ_L5L6XXB_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L5L6B_L3PHIC_04MOD.dat")
) TPROJ_L5L6XXB_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_din;
reg TPROJ_L5L6XXD_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_0_V_din;
reg TPROJ_L5L6XXD_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L5L6XXD_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L5L6XXD_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L5L6XXD_L3PHIC_nentreg_0 = 8'b00000001; // 1
reg[7:0] TPROJ_L5L6XXD_L3PHIC_nentreg_1 = 8'b00000100; // 4
assign TPROJ_L5L6XXD_L3PHIC_nentries_0_V_din = TPROJ_L5L6XXD_L3PHIC_nentreg_0;
assign TPROJ_L5L6XXD_L3PHIC_nentries_1_V_din = TPROJ_L5L6XXD_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L5L6D_L3PHIC_04MOD.dat")
) TPROJ_L5L6XXD_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_din;
reg TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_din;
reg TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L1L2XXJ_L3PHIC_nentreg_0 = 8'b00000100; // 4
reg[7:0] TPROJ_L1L2XXJ_L3PHIC_nentreg_1 = 8'b00001111; // 15
assign TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_din = TPROJ_L1L2XXJ_L3PHIC_nentreg_0;
assign TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_din = TPROJ_L1L2XXJ_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L1L2J_L3PHIC_04MOD.dat")
) TPROJ_L1L2XXJ_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_din;
reg TPROJ_L1L2XXG_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_0_V_din;
reg TPROJ_L1L2XXG_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXG_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L1L2XXG_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L1L2XXG_L3PHIC_nentreg_0 = 8'b00010111; // 23
reg[7:0] TPROJ_L1L2XXG_L3PHIC_nentreg_1 = 8'b00001111; // 15
assign TPROJ_L1L2XXG_L3PHIC_nentries_0_V_din = TPROJ_L1L2XXG_L3PHIC_nentreg_0;
assign TPROJ_L1L2XXG_L3PHIC_nentries_1_V_din = TPROJ_L1L2XXG_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L1L2G_L3PHIC_04MOD.dat")
) TPROJ_L1L2XXG_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

reg TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_din;
reg TPROJ_L1L2XXF_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_0_V_din;
reg TPROJ_L1L2XXF_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXF_L3PHIC_nentries_0_V_we = 1'b1;
  TPROJ_L1L2XXF_L3PHIC_nentries_1_V_we = 1'b1;
end

reg[7:0] TPROJ_L1L2XXF_L3PHIC_nentreg_0 = 8'b00000001; // 1
reg[7:0] TPROJ_L1L2XXF_L3PHIC_nentreg_1 = 8'b00000000; // 0
assign TPROJ_L1L2XXF_L3PHIC_nentries_0_V_din = TPROJ_L1L2XXF_L3PHIC_nentreg_0;
assign TPROJ_L1L2XXF_L3PHIC_nentries_1_V_din = TPROJ_L1L2XXF_L3PHIC_nentreg_1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(1),
  .INIT_FILE("TrackletProjections_TPROJ_L1L2F_L3PHIC_04MOD.dat")
) TPROJ_L1L2XXF_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_wea),
  .addra(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_writeaddr),
  .dina(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_din),
  .nent_we0(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_we),
  .nent_i0(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_din),
  .nent_we1(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_we),
  .nent_i1(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_din),
  .enb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb),
  .addrb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr),
  .doutb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout),
  .nent_o0(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout),
  .nent_o1(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

// ME Inputs
reg VMSME_L3PHIC17to24n1_dataarray_data_V_wea [7:0];
wire[7:0] VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr [7:0];
wire[13:0] VMSME_L3PHIC17to24n1_dataarray_data_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_0_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_0_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_1_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_1_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_2_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_2_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_3_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_3_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_4_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_4_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_5_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_5_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_6_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_6_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_0_7_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_7_V_din [7:0];
reg VMSME_L3PHIC17to24n1_nentries_1_0_V_we [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_0_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_1_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_1_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_2_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_2_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_3_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_3_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_4_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_4_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_5_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_5_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_6_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_6_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_1_7_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_1_7_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_0_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_0_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_1_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_1_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_2_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_2_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_3_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_3_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_4_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_4_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_5_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_5_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_6_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_6_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_2_7_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_2_7_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_0_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_0_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_1_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_1_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_2_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_2_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_3_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_3_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_4_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_4_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_5_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_5_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_6_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_6_V_din [7:0];
reg 	VMSME_L3PHIC17to24n1_nentries_3_7_V_we [7:0];
wire [3:0] VMSME_L3PHIC17to24n1_nentries_3_7_V_din [7:0];
wire VMSME_L3PHIC17to24n1_dataarray_data_V_enb [7:0];
wire[8:0] VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr [7:0];
wire[13:0] VMSME_L3PHIC17to24n1_dataarray_data_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_0_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_1_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_2_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_3_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_4_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_5_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_6_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_0_7_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_0_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_1_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_2_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_3_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_4_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_5_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_6_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_1_7_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_0_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_1_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_2_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_3_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_4_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_5_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_6_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_2_7_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_0_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_1_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_2_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_3_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_4_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_5_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_6_V_dout [7:0];
wire[3:0] VMSME_L3PHIC17to24n1_nentries_3_7_V_dout [7:0];
   

initial begin
  VMSME_L3PHIC17to24n1_nentries_0_0_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_1_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_2_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_3_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_4_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_5_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_6_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
  VMSME_L3PHIC17to24n1_nentries_0_7_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_0_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_1_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_2_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_3_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_4_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_5_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_6_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_1_7_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_0_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_1_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_2_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_3_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_4_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_5_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_6_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_2_7_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_0_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_1_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_2_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_3_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_4_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_5_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_6_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
   VMSME_L3PHIC17to24n1_nentries_3_7_V_we = {1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1,1'b1};
end

reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_0 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_1 [7:0] = {4'b0010, 4'b0101, 4'b0000, 4'b0010, 4'b0100, 4'b0001, 4'b0000, 4'b0000}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_2 [7:0] = {4'b0000, 4'b0001, 4'b0010, 4'b0010, 4'b0010, 4'b0001, 4'b0000, 4'b0000}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_3 [7:0] = {4'b0001, 4'b0001, 4'b0011, 4'b0001, 4'b0011, 4'b0100, 4'b0100, 4'b0011}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_4 [7:0] = {4'b0010, 4'b0010, 4'b0011, 4'b0000, 4'b0000, 4'b0100, 4'b0011, 4'b0001}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_5 [7:0] = {4'b0001, 4'b0001, 4'b0110, 4'b0010, 4'b0010, 4'b0001, 4'b0010, 4'b0001}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_6 [7:0] = {4'b0000, 4'b0001, 4'b0000, 4'b0000, 4'b0010, 4'b0011, 4'b0000, 4'b0000}; // FIX
reg[3:0] VMSME_L3PHIC17to24n1_nentreg_0_7 [7:0] = {4'b0010, 4'b0011, 4'b0001, 4'b0000, 4'b0000, 4'b0001, 4'b0000, 4'b0001}; // FIX
assign VMSME_L3PHIC17to24n1_nentries_0_0_V_din = VMSME_L3PHIC17to24n1_nentreg_0_0;
assign VMSME_L3PHIC17to24n1_nentries_0_1_V_din = VMSME_L3PHIC17to24n1_nentreg_0_1;
assign VMSME_L3PHIC17to24n1_nentries_0_2_V_din = VMSME_L3PHIC17to24n1_nentreg_0_2;
assign VMSME_L3PHIC17to24n1_nentries_0_3_V_din = VMSME_L3PHIC17to24n1_nentreg_0_3;
assign VMSME_L3PHIC17to24n1_nentries_0_4_V_din = VMSME_L3PHIC17to24n1_nentreg_0_4;
assign VMSME_L3PHIC17to24n1_nentries_0_5_V_din = VMSME_L3PHIC17to24n1_nentreg_0_5;
assign VMSME_L3PHIC17to24n1_nentries_0_6_V_din = VMSME_L3PHIC17to24n1_nentreg_0_6;
assign VMSME_L3PHIC17to24n1_nentries_0_7_V_din = VMSME_L3PHIC17to24n1_nentreg_0_7;
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_0 [7:0] = {4'b0010, 4'b0001, 4'b0001, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_1 [7:0] = {4'b0000, 4'b0000, 4'b0001, 4'b0000, 4'b0000, 4'b0001, 4'b0010, 4'b0001}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_2 [7:0] = {4'b0000, 4'b0001, 4'b0010, 4'b0010, 4'b0000, 4'b0001, 4'b0001, 4'b0010}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_3 [7:0] = {4'b0011, 4'b0100, 4'b0001, 4'b0000, 4'b0010, 4'b0100, 4'b0010, 4'b0010}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_4 [7:0] = {4'b0100, 4'b0011, 4'b0010, 4'b0001, 4'b0010, 4'b0010, 4'b0010, 4'b0100}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_5 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0010, 4'b0001, 4'b0001, 4'b0010, 4'b0100}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_6 [7:0] = {4'b0011, 4'b0001, 4'b0010, 4'b0001, 4'b0000, 4'b0000, 4'b0001, 4'b0001}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_1_7 [7:0] = {4'b0000, 4'b0000, 4'b0001, 4'b0001, 4'b0000, 4'b0100, 4'b0101, 4'b0000}; // FIX
assign VMSME_L3PHIC17to24n1_nentries_1_0_V_din = VMSME_L3PHIC17to24n1_nentreg_1_0;
assign VMSME_L3PHIC17to24n1_nentries_1_1_V_din = VMSME_L3PHIC17to24n1_nentreg_1_1;
assign VMSME_L3PHIC17to24n1_nentries_1_2_V_din = VMSME_L3PHIC17to24n1_nentreg_1_2;
assign VMSME_L3PHIC17to24n1_nentries_1_3_V_din = VMSME_L3PHIC17to24n1_nentreg_1_3;
assign VMSME_L3PHIC17to24n1_nentries_1_4_V_din = VMSME_L3PHIC17to24n1_nentreg_1_4;
assign VMSME_L3PHIC17to24n1_nentries_1_5_V_din = VMSME_L3PHIC17to24n1_nentreg_1_5;
assign VMSME_L3PHIC17to24n1_nentries_1_6_V_din = VMSME_L3PHIC17to24n1_nentreg_1_6;
assign VMSME_L3PHIC17to24n1_nentries_1_7_V_din = VMSME_L3PHIC17to24n1_nentreg_1_7;
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_0 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_1 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_2 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_3 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_4 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_5 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_6 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_2_7 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
assign VMSME_L3PHIC17to24n1_nentries_2_0_V_din = VMSME_L3PHIC17to24n1_nentreg_2_0;
assign VMSME_L3PHIC17to24n1_nentries_2_1_V_din = VMSME_L3PHIC17to24n1_nentreg_2_1;
assign VMSME_L3PHIC17to24n1_nentries_2_2_V_din = VMSME_L3PHIC17to24n1_nentreg_2_2;
assign VMSME_L3PHIC17to24n1_nentries_2_3_V_din = VMSME_L3PHIC17to24n1_nentreg_2_3;
assign VMSME_L3PHIC17to24n1_nentries_2_4_V_din = VMSME_L3PHIC17to24n1_nentreg_2_4;
assign VMSME_L3PHIC17to24n1_nentries_2_5_V_din = VMSME_L3PHIC17to24n1_nentreg_2_5;
assign VMSME_L3PHIC17to24n1_nentries_2_6_V_din = VMSME_L3PHIC17to24n1_nentreg_2_6;
assign VMSME_L3PHIC17to24n1_nentries_2_7_V_din = VMSME_L3PHIC17to24n1_nentreg_2_7;
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_0 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_1 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_2 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_3 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_4 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_5 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_6 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
reg [3:0] VMSME_L3PHIC17to24n1_nentreg_3_7 [7:0] = {4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000, 4'b0000}; // FIX
assign VMSME_L3PHIC17to24n1_nentries_3_0_V_din = VMSME_L3PHIC17to24n1_nentreg_3_0;
assign VMSME_L3PHIC17to24n1_nentries_3_1_V_din = VMSME_L3PHIC17to24n1_nentreg_3_1;
assign VMSME_L3PHIC17to24n1_nentries_3_2_V_din = VMSME_L3PHIC17to24n1_nentreg_3_2;
assign VMSME_L3PHIC17to24n1_nentries_3_3_V_din = VMSME_L3PHIC17to24n1_nentreg_3_3;
assign VMSME_L3PHIC17to24n1_nentries_3_4_V_din = VMSME_L3PHIC17to24n1_nentreg_3_4;
assign VMSME_L3PHIC17to24n1_nentries_3_5_V_din = VMSME_L3PHIC17to24n1_nentreg_3_5;
assign VMSME_L3PHIC17to24n1_nentries_3_6_V_din = VMSME_L3PHIC17to24n1_nentreg_3_6;
assign VMSME_L3PHIC17to24n1_nentries_3_7_V_din = VMSME_L3PHIC17to24n1_nentreg_3_7;

// // // // // // // //    

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC17n1_04MOD.dat")
) VMSME_L3PHIC17n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[0]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[0]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[0]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[0]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[0]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[0]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[0]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[0]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[0]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[0]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[0]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[0]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[0]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[0]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[0]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[0]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[0]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[0]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[0]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[0]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[0]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[0]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[0]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[0]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[0]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[0]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[0]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[0]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[0]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[0]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[0]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[0]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[0]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[0]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[0]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[0]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[0]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[0]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[0]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[0]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[0]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[0]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[0]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[0]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[0]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[0]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[0]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[0]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[0]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[0]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[0]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[0]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[0]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[0]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[0]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[0]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[0]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[0]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[0]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[0]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[0]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[0]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[0]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[0]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[0]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[0]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[0]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[0]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[0][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[0]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[0]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[0]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[0]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[0]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[0]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[0]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[0]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[0]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[0]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[0]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[0]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[0]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[0]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[0]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[0]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[0]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[0]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[0]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[0]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[0]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[0]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[0]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[0]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[0]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[0]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[0]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[0]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[0]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[0]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[0]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[0]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[0]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC18n1_04MOD.dat")
) VMSME_L3PHIC18n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[1]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[1]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[1]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[1]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[1]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[1]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[1]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[1]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[1]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[1]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[1]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[1]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[1]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[1]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[1]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[1]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[1]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[1]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[1]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[1]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[1]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[1]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[1]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[1]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[1]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[1]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[1]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[1]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[1]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[1]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[1]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[1]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[1]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[1]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[1]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[1]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[1]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[1]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[1]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[1]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[1]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[1]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[1]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[1]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[1]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[1]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[1]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[1]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[1]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[1]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[1]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[1]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[1]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[1]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[1]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[1]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[1]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[1]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[1]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[1]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[1]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[1]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[1]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[1]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[1]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[1]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[1]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[1]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[1][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[1]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[1]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[1]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[1]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[1]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[1]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[1]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[1]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[1]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[1]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[1]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[1]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[1]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[1]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[1]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[1]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[1]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[1]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[1]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[1]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[1]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[1]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[1]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[1]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[1]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[1]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[1]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[1]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[1]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[1]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[1]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[1]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[1]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC19n1_04MOD.dat")
) VMSME_L3PHIC19n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[2]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[2]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[2]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[2]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[2]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[2]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[2]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[2]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[2]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[2]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[2]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[2]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[2]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[2]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[2]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[2]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[2]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[2]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[2]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[2]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[2]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[2]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[2]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[2]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[2]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[2]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[2]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[2]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[2]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[2]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[2]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[2]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[2]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[2]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[2]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[2]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[2]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[2]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[2]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[2]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[2]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[2]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[2]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[2]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[2]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[2]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[2]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[2]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[2]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[2]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[2]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[2]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[2]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[2]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[2]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[2]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[2]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[2]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[2]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[2]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[2]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[2]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[2]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[2]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[2]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[2]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[2]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[2]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[2][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[2]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[2]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[2]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[2]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[2]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[2]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[2]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[2]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[2]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[2]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[2]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[2]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[2]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[2]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[2]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[2]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[2]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[2]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[2]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[2]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[2]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[2]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[2]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[2]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[2]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[2]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[2]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[2]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[2]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[2]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[2]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[2]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[2]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC20n1_04MOD.dat")
) VMSME_L3PHIC20n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[3]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[3]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[3]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[3]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[3]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[3]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[3]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[3]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[3]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[3]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[3]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[3]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[3]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[3]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[3]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[3]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[3]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[3]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[3]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[3]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[3]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[3]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[3]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[3]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[3]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[3]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[3]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[3]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[3]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[3]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[3]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[3]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[3]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[3]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[3]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[3]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[3]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[3]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[3]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[3]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[3]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[3]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[3]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[3]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[3]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[3]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[3]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[3]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[3]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[3]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[3]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[3]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[3]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[3]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[3]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[3]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[3]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[3]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[3]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[3]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[3]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[3]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[3]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[3]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[3]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[3]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[3]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[3]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[3][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[3]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[3]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[3]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[3]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[3]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[3]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[3]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[3]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[3]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[3]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[3]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[3]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[3]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[3]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[3]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[3]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[3]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[3]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[3]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[3]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[3]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[3]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[3]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[3]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[3]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[3]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[3]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[3]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[3]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[3]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[3]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[3]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[3]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC21n1_04MOD.dat")
) VMSME_L3PHIC21n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[4]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[4]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[4]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[4]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[4]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[4]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[4]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[4]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[4]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[4]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[4]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[4]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[4]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[4]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[4]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[4]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[4]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[4]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[4]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[4]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[4]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[4]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[4]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[4]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[4]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[4]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[4]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[4]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[4]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[4]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[4]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[4]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[4]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[4]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[4]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[4]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[4]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[4]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[4]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[4]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[4]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[4]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[4]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[4]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[4]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[4]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[4]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[4]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[4]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[4]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[4]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[4]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[4]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[4]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[4]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[4]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[4]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[4]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[4]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[4]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[4]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[4]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[4]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[4]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[4]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[4]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[4]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[4]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[4][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[4]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[4]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[4]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[4]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[4]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[4]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[4]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[4]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[4]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[4]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[4]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[4]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[4]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[4]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[4]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[4]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[4]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[4]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[4]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[4]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[4]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[4]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[4]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[4]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[4]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[4]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[4]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[4]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[4]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[4]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[4]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[4]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[4]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC22n1_04MOD.dat")
) VMSME_L3PHIC22n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[5]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[5]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[5]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[5]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[5]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[5]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[5]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[5]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[5]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[5]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[5]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[5]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[5]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[5]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[5]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[5]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[5]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[5]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[5]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[5]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[5]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[5]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[5]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[5]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[5]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[5]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[5]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[5]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[5]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[5]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[5]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[5]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[5]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[5]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[5]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[5]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[5]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[5]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[5]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[5]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[5]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[5]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[5]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[5]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[5]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[5]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[5]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[5]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[5]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[5]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[5]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[5]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[5]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[5]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[5]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[5]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[5]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[5]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[5]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[5]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[5]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[5]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[5]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[5]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[5]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[5]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[5]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[5]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[5][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[5]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[5]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[5]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[5]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[5]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[5]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[5]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[5]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[5]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[5]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[5]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[5]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[5]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[5]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[5]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[5]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[5]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[5]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[5]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[5]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[5]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[5]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[5]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[5]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[5]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[5]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[5]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[5]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[5]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[5]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[5]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[5]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[5]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC23n1_04MOD.dat")
) VMSME_L3PHIC23n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[6]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[6]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[6]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[6]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[6]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[6]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[6]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[6]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[6]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[6]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[6]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[6]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[6]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[6]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[6]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[6]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[6]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[6]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[6]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[6]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[6]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[6]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[6]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[6]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[6]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[6]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[6]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[6]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[6]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[6]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[6]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[6]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[6]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[6]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[6]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[6]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[6]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[6]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[6]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[6]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[6]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[6]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[6]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[6]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[6]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[6]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[6]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[6]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[6]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[6]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[6]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[6]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[6]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[6]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[6]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[6]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[6]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[6]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[6]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[6]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[6]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[6]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[6]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[6]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[6]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[6]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[6]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[6]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[6][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[6]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[6]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[6]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[6]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[6]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[6]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[6]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[6]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[6]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[6]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[6]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[6]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[6]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[6]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[6]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[6]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[6]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[6]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[6]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[6]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[6]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[6]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[6]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[6]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[6]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[6]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[6]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[6]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[6]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[6]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[6]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[6]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[6]),		    
  .regceb(1'b1)
);

MemoryBinned #(
  .RAM_WIDTH(14),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("LOW_LATENCY"),
  .HEX(1),
  .INIT_FILE("VMStubs_VMSME_L3PHIC24n1_04MOD.dat")
) VMSME_L3PHIC24n1 (
  .clka(clk),
  .clkb(clk),
  .rstb(1'b0),
  .wea(VMSME_L3PHIC17to24n1_dataarray_data_V_wea[7]),
  .addra(VMSME_L3PHIC17to24n1_dataarray_data_V_writeaddr[7]),
  .dina(VMSME_L3PHIC17to24n1_dataarray_data_V_din[7]),
  .nent_0_we0(VMSME_L3PHIC17to24n1_nentries_0_0_V_we[7]),
  .nent_0_i0(VMSME_L3PHIC17to24n1_nentries_0_0_V_din[7]),
  .nent_0_we1(VMSME_L3PHIC17to24n1_nentries_0_1_V_we[7]),
  .nent_0_i1(VMSME_L3PHIC17to24n1_nentries_0_1_V_din[7]),
  .nent_0_we2(VMSME_L3PHIC17to24n1_nentries_0_2_V_we[7]),
  .nent_0_i2(VMSME_L3PHIC17to24n1_nentries_0_2_V_din[7]),
  .nent_0_we3(VMSME_L3PHIC17to24n1_nentries_0_3_V_we[7]),
  .nent_0_i3(VMSME_L3PHIC17to24n1_nentries_0_3_V_din[7]),
  .nent_0_we4(VMSME_L3PHIC17to24n1_nentries_0_4_V_we[7]),
  .nent_0_i4(VMSME_L3PHIC17to24n1_nentries_0_4_V_din[7]),
  .nent_0_we5(VMSME_L3PHIC17to24n1_nentries_0_5_V_we[7]),
  .nent_0_i5(VMSME_L3PHIC17to24n1_nentries_0_5_V_din[7]),
  .nent_0_we6(VMSME_L3PHIC17to24n1_nentries_0_6_V_we[7]),
  .nent_0_i6(VMSME_L3PHIC17to24n1_nentries_0_6_V_din[7]),
  .nent_0_we7(VMSME_L3PHIC17to24n1_nentries_0_7_V_we[7]),
  .nent_0_i7(VMSME_L3PHIC17to24n1_nentries_0_7_V_din[7]),
  .nent_1_we0(VMSME_L3PHIC17to24n1_nentries_1_0_V_we[7]),
  .nent_1_i0(VMSME_L3PHIC17to24n1_nentries_1_0_V_din[7]),
  .nent_1_we1(VMSME_L3PHIC17to24n1_nentries_1_1_V_we[7]),
  .nent_1_i1(VMSME_L3PHIC17to24n1_nentries_1_1_V_din[7]),
  .nent_1_we2(VMSME_L3PHIC17to24n1_nentries_1_2_V_we[7]),
  .nent_1_i2(VMSME_L3PHIC17to24n1_nentries_1_2_V_din[7]),
  .nent_1_we3(VMSME_L3PHIC17to24n1_nentries_1_3_V_we[7]),
  .nent_1_i3(VMSME_L3PHIC17to24n1_nentries_1_3_V_din[7]),
  .nent_1_we4(VMSME_L3PHIC17to24n1_nentries_1_4_V_we[7]),
  .nent_1_i4(VMSME_L3PHIC17to24n1_nentries_1_4_V_din[7]),
  .nent_1_we5(VMSME_L3PHIC17to24n1_nentries_1_5_V_we[7]),
  .nent_1_i5(VMSME_L3PHIC17to24n1_nentries_1_5_V_din[7]),
  .nent_1_we6(VMSME_L3PHIC17to24n1_nentries_1_6_V_we[7]),
  .nent_1_i6(VMSME_L3PHIC17to24n1_nentries_1_6_V_din[7]),
  .nent_1_we7(VMSME_L3PHIC17to24n1_nentries_1_7_V_we[7]),
  .nent_1_i7(VMSME_L3PHIC17to24n1_nentries_1_7_V_din[7]),
  .nent_2_we0(VMSME_L3PHIC17to24n1_nentries_2_0_V_we[7]),
  .nent_2_i0(VMSME_L3PHIC17to24n1_nentries_2_0_V_din[7]),
  .nent_2_we1(VMSME_L3PHIC17to24n1_nentries_2_1_V_we[7]),
  .nent_2_i1(VMSME_L3PHIC17to24n1_nentries_2_1_V_din[7]),
  .nent_2_we2(VMSME_L3PHIC17to24n1_nentries_2_2_V_we[7]),
  .nent_2_i2(VMSME_L3PHIC17to24n1_nentries_2_2_V_din[7]),
  .nent_2_we3(VMSME_L3PHIC17to24n1_nentries_2_3_V_we[7]),
  .nent_2_i3(VMSME_L3PHIC17to24n1_nentries_2_3_V_din[7]),
  .nent_2_we4(VMSME_L3PHIC17to24n1_nentries_2_4_V_we[7]),
  .nent_2_i4(VMSME_L3PHIC17to24n1_nentries_2_4_V_din[7]),
  .nent_2_we5(VMSME_L3PHIC17to24n1_nentries_2_5_V_we[7]),
  .nent_2_i5(VMSME_L3PHIC17to24n1_nentries_2_5_V_din[7]),
  .nent_2_we6(VMSME_L3PHIC17to24n1_nentries_2_6_V_we[7]),
  .nent_2_i6(VMSME_L3PHIC17to24n1_nentries_2_6_V_din[7]),
  .nent_2_we7(VMSME_L3PHIC17to24n1_nentries_2_7_V_we[7]),
  .nent_2_i7(VMSME_L3PHIC17to24n1_nentries_2_7_V_din[7]),
  .nent_3_we0(VMSME_L3PHIC17to24n1_nentries_3_0_V_we[7]),
  .nent_3_i0(VMSME_L3PHIC17to24n1_nentries_3_0_V_din[7]),
  .nent_3_we1(VMSME_L3PHIC17to24n1_nentries_3_1_V_we[7]),
  .nent_3_i1(VMSME_L3PHIC17to24n1_nentries_3_1_V_din[7]),
  .nent_3_we2(VMSME_L3PHIC17to24n1_nentries_3_2_V_we[7]),
  .nent_3_i2(VMSME_L3PHIC17to24n1_nentries_3_2_V_din[7]),
  .nent_3_we3(VMSME_L3PHIC17to24n1_nentries_3_3_V_we[7]),
  .nent_3_i3(VMSME_L3PHIC17to24n1_nentries_3_3_V_din[7]),
  .nent_3_we4(VMSME_L3PHIC17to24n1_nentries_3_4_V_we[7]),
  .nent_3_i4(VMSME_L3PHIC17to24n1_nentries_3_4_V_din[7]),
  .nent_3_we5(VMSME_L3PHIC17to24n1_nentries_3_5_V_we[7]),
  .nent_3_i5(VMSME_L3PHIC17to24n1_nentries_3_5_V_din[7]),
  .nent_3_we6(VMSME_L3PHIC17to24n1_nentries_3_6_V_we[7]),
  .nent_3_i6(VMSME_L3PHIC17to24n1_nentries_3_6_V_din[7]),
  .nent_3_we7(VMSME_L3PHIC17to24n1_nentries_3_7_V_we[7]),
  .nent_3_i7(VMSME_L3PHIC17to24n1_nentries_3_7_V_din[7]),		    
  .enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb[7]),
  .addrb(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr[7][7:0]),
  .doutb(VMSME_L3PHIC17to24n1_dataarray_data_V_dout[7]),
  .nent_0_o0(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout[7]),
  .nent_0_o1(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout[7]),
  .nent_0_o2(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout[7]),
  .nent_0_o3(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout[7]),
  .nent_0_o4(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout[7]),
  .nent_0_o5(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout[7]),
  .nent_0_o6(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout[7]),
  .nent_0_o7(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout[7]),
  .nent_1_o0(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout[7]),
  .nent_1_o1(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout[7]),
  .nent_1_o2(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout[7]),
  .nent_1_o3(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout[7]),
  .nent_1_o4(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout[7]),
  .nent_1_o5(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout[7]),
  .nent_1_o6(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout[7]),
  .nent_1_o7(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout[7]),
  .nent_2_o0(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout[7]),
  .nent_2_o1(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout[7]),
  .nent_2_o2(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout[7]),
  .nent_2_o3(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout[7]),
  .nent_2_o4(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout[7]),
  .nent_2_o5(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout[7]),
  .nent_2_o6(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout[7]),
  .nent_2_o7(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout[7]),
  .nent_3_o0(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout[7]),
  .nent_3_o1(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout[7]),
  .nent_3_o2(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout[7]),
  .nent_3_o3(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout[7]),
  .nent_3_o4(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout[7]),
  .nent_3_o5(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout[7]),
  .nent_3_o6(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout[7]),
  .nent_3_o7(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout[7]),		    
  .regceb(1'b1)
);

wire FM_L1L2XX_L3PHIC_dataarray_data_V_wea;
wire[7:0] FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FM_L1L2XX_L3PHIC_dataarray_data_V_din;
wire FM_L1L2XX_L3PHIC_nentries_0_V_we;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_0_V_din;
wire FM_L1L2XX_L3PHIC_nentries_1_V_we;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_1_V_din;
wire FM_L1L2XX_L3PHIC_dataarray_data_V_enb;
wire[7:0] FM_L1L2XX_L3PHIC_dataarray_data_V_readaddr;
wire[44:0] FM_L1L2XX_L3PHIC_dataarray_data_V_dout;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_0_V_dout;
wire[7:0] FM_L1L2XX_L3PHIC_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FM_L1L2XX_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FM_L1L2XX_L3PHIC_dataarray_data_V_wea),
  .addra(FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FM_L1L2XX_L3PHIC_dataarray_data_V_din),
  .nent_we0(FM_L1L2XX_L3PHIC_nentries_0_V_we),
  .nent_i0(FM_L1L2XX_L3PHIC_nentries_0_V_din),
  .nent_we1(FM_L1L2XX_L3PHIC_nentries_1_V_we),
  .nent_i1(FM_L1L2XX_L3PHIC_nentries_1_V_din),
  .enb(FM_L1L2XX_L3PHIC_dataarray_data_V_enb),
  .addrb(FM_L1L2XX_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FM_L1L2XX_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FM_L1L2XX_L3PHIC_nentries_0_V_dout),
  .nent_o1(FM_L1L2XX_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire FM_L5L6XX_L3PHIC_dataarray_data_V_wea;
wire[7:0] FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr;
wire[44:0] FM_L5L6XX_L3PHIC_dataarray_data_V_din;
wire FM_L5L6XX_L3PHIC_nentries_0_V_we;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_0_V_din;
wire FM_L5L6XX_L3PHIC_nentries_1_V_we;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_1_V_din;
wire FM_L5L6XX_L3PHIC_dataarray_data_V_enb;
wire[7:0] FM_L5L6XX_L3PHIC_dataarray_data_V_readaddr;
wire[44:0] FM_L5L6XX_L3PHIC_dataarray_data_V_dout;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_0_V_dout;
wire[7:0] FM_L5L6XX_L3PHIC_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(45),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) FM_L5L6XX_L3PHIC (
  .clka(clk),
  .clkb(clk),
  .wea(FM_L5L6XX_L3PHIC_dataarray_data_V_wea),
  .addra(FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr),
  .dina(FM_L5L6XX_L3PHIC_dataarray_data_V_din),
  .nent_we0(FM_L5L6XX_L3PHIC_nentries_0_V_we),
  .nent_i0(FM_L5L6XX_L3PHIC_nentries_0_V_din),
  .nent_we1(FM_L5L6XX_L3PHIC_nentries_1_V_we),
  .nent_i1(FM_L5L6XX_L3PHIC_nentries_1_V_din),
  .enb(FM_L5L6XX_L3PHIC_dataarray_data_V_enb),
  .addrb(FM_L5L6XX_L3PHIC_dataarray_data_V_readaddr),
  .doutb(FM_L5L6XX_L3PHIC_dataarray_data_V_dout),
  .nent_o0(FM_L5L6XX_L3PHIC_nentries_0_V_dout),
  .nent_o1(FM_L5L6XX_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);
                        

uut uut_inst (
  .clk(clk),
  .reset(reset),
  .en_proc(en_proc),
  .bx_in_ProjectionRouter(bx_in_ProjectionRouter),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout),
  .VMSME_L3PHIC17to24n1_dataarray_data_V_enb(VMSME_L3PHIC17to24n1_dataarray_data_V_enb),
  .VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr(VMSME_L3PHIC17to24n1_dataarray_data_V_readaddr),
  .VMSME_L3PHIC17to24n1_dataarray_data_V_dout(VMSME_L3PHIC17to24n1_dataarray_data_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_0_V_dout(VMSME_L3PHIC17to24n1_nentries_0_0_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_1_V_dout(VMSME_L3PHIC17to24n1_nentries_0_1_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_2_V_dout(VMSME_L3PHIC17to24n1_nentries_0_2_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_3_V_dout(VMSME_L3PHIC17to24n1_nentries_0_3_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_4_V_dout(VMSME_L3PHIC17to24n1_nentries_0_4_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_5_V_dout(VMSME_L3PHIC17to24n1_nentries_0_5_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_6_V_dout(VMSME_L3PHIC17to24n1_nentries_0_6_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_0_7_V_dout(VMSME_L3PHIC17to24n1_nentries_0_7_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_0_V_dout(VMSME_L3PHIC17to24n1_nentries_1_0_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_1_V_dout(VMSME_L3PHIC17to24n1_nentries_1_1_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_2_V_dout(VMSME_L3PHIC17to24n1_nentries_1_2_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_3_V_dout(VMSME_L3PHIC17to24n1_nentries_1_3_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_4_V_dout(VMSME_L3PHIC17to24n1_nentries_1_4_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_5_V_dout(VMSME_L3PHIC17to24n1_nentries_1_5_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_6_V_dout(VMSME_L3PHIC17to24n1_nentries_1_6_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_1_7_V_dout(VMSME_L3PHIC17to24n1_nentries_1_7_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_0_V_dout(VMSME_L3PHIC17to24n1_nentries_2_0_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_1_V_dout(VMSME_L3PHIC17to24n1_nentries_2_1_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_2_V_dout(VMSME_L3PHIC17to24n1_nentries_2_2_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_3_V_dout(VMSME_L3PHIC17to24n1_nentries_2_3_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_4_V_dout(VMSME_L3PHIC17to24n1_nentries_2_4_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_5_V_dout(VMSME_L3PHIC17to24n1_nentries_2_5_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_6_V_dout(VMSME_L3PHIC17to24n1_nentries_2_6_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_2_7_V_dout(VMSME_L3PHIC17to24n1_nentries_2_7_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_0_V_dout(VMSME_L3PHIC17to24n1_nentries_3_0_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_1_V_dout(VMSME_L3PHIC17to24n1_nentries_3_1_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_2_V_dout(VMSME_L3PHIC17to24n1_nentries_3_2_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_3_V_dout(VMSME_L3PHIC17to24n1_nentries_3_3_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_4_V_dout(VMSME_L3PHIC17to24n1_nentries_3_4_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_5_V_dout(VMSME_L3PHIC17to24n1_nentries_3_5_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_6_V_dout(VMSME_L3PHIC17to24n1_nentries_3_6_V_dout),
  .VMSME_L3PHIC17to24n1_nentries_3_7_V_dout(VMSME_L3PHIC17to24n1_nentries_3_7_V_dout),	
  .AS_L3PHICn4_dataarray_data_V_enb(AS_L3PHICn4_dataarray_data_V_enb),
  .AS_L3PHICn4_dataarray_data_V_readaddr(AS_L3PHICn4_dataarray_data_V_readaddr),
  .AS_L3PHICn4_dataarray_data_V_dout(AS_L3PHICn4_dataarray_data_V_dout),
  .AS_L3PHICn4_nentries_0_V_dout(AS_L3PHICn4_nentries_0_V_dout),
  .AS_L3PHICn4_nentries_1_V_dout(AS_L3PHICn4_nentries_1_V_dout),
  .AS_L3PHICn4_nentries_2_V_dout(AS_L3PHICn4_nentries_2_V_dout),
  .AS_L3PHICn4_nentries_3_V_dout(AS_L3PHICn4_nentries_3_V_dout),
  .AS_L3PHICn4_nentries_4_V_dout(AS_L3PHICn4_nentries_4_V_dout),
  .AS_L3PHICn4_nentries_5_V_dout(AS_L3PHICn4_nentries_5_V_dout),
  .AS_L3PHICn4_nentries_6_V_dout(AS_L3PHICn4_nentries_6_V_dout),
  .AS_L3PHICn4_nentries_7_V_dout(AS_L3PHICn4_nentries_7_V_dout),			      
  .FM_L1L2XX_L3PHIC_dataarray_data_V_wea(FM_L1L2XX_L3PHIC_dataarray_data_V_wea),
  .FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr(FM_L1L2XX_L3PHIC_dataarray_data_V_writeaddr),
  .FM_L1L2XX_L3PHIC_dataarray_data_V_din(FM_L1L2XX_L3PHIC_dataarray_data_V_din),
  .FM_L1L2XX_L3PHIC_nentries_0_V_we(FM_L1L2XX_L3PHIC_nentries_0_V_we),
  .FM_L1L2XX_L3PHIC_nentries_0_V_din(FM_L1L2XX_L3PHIC_nentries_0_V_din),
  .FM_L1L2XX_L3PHIC_nentries_1_V_we(FM_L1L2XX_L3PHIC_nentries_1_V_we),
  .FM_L1L2XX_L3PHIC_nentries_1_V_din(FM_L1L2XX_L3PHIC_nentries_1_V_din),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_wea(FM_L5L6XX_L3PHIC_dataarray_data_V_wea),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr(FM_L5L6XX_L3PHIC_dataarray_data_V_writeaddr),
  .FM_L5L6XX_L3PHIC_dataarray_data_V_din(FM_L5L6XX_L3PHIC_dataarray_data_V_din),
  .FM_L5L6XX_L3PHIC_nentries_0_V_we(FM_L5L6XX_L3PHIC_nentries_0_V_we),
  .FM_L5L6XX_L3PHIC_nentries_0_V_din(FM_L5L6XX_L3PHIC_nentries_0_V_din),
  .FM_L5L6XX_L3PHIC_nentries_1_V_we(FM_L5L6XX_L3PHIC_nentries_1_V_we),
  .FM_L5L6XX_L3PHIC_nentries_1_V_din(FM_L5L6XX_L3PHIC_nentries_1_V_din),
  .bx_out_MatchCalculator(bx_out_MatchCalculator),
  .MatchCalculator_done(MatchCalculator_done)
);

endmodule
