// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _VMRouterDispatcher_AddStub_HH_
#define _VMRouterDispatcher_AddStub_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct VMRouterDispatcher_AddStub : public sc_module {
    // Port declarations 10
    sc_in< sc_lv<4> > HLSReducedStubLayer_z_V_write;
    sc_in< sc_lv<3> > HLSReducedStubLayer_phi_V_write;
    sc_in< sc_lv<2> > HLSReducedStubLayer_r_V_write;
    sc_in< sc_lv<3> > HLSReducedStubLayer_pt_V_write;
    sc_in< sc_lv<6> > HLSReducedStubLayer_index_V_write;
    sc_out< sc_lv<4> > ap_return_0;
    sc_out< sc_lv<3> > ap_return_1;
    sc_out< sc_lv<2> > ap_return_2;
    sc_out< sc_lv<3> > ap_return_3;
    sc_out< sc_lv<6> > ap_return_4;


    // Module declarations
    VMRouterDispatcher_AddStub(sc_module_name name);
    SC_HAS_PROCESS(VMRouterDispatcher_AddStub);

    ~VMRouterDispatcher_AddStub();

    sc_trace_file* mVcdFile;

    static const bool ap_true;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
};

}

using namespace ap_rtl;

#endif
