// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module VMRouterDispatcher_AddStub (
        HLSReducedStubLayer_z_V_write,
        HLSReducedStubLayer_phi_V_write,
        HLSReducedStubLayer_r_V_write,
        HLSReducedStubLayer_pt_V_write,
        HLSReducedStubLayer_index_V_write,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


input  [3:0] HLSReducedStubLayer_z_V_write;
input  [2:0] HLSReducedStubLayer_phi_V_write;
input  [1:0] HLSReducedStubLayer_r_V_write;
input  [2:0] HLSReducedStubLayer_pt_V_write;
input  [5:0] HLSReducedStubLayer_index_V_write;
output  [3:0] ap_return_0;
output  [2:0] ap_return_1;
output  [1:0] ap_return_2;
output  [2:0] ap_return_3;
output  [5:0] ap_return_4;

assign ap_return_0 = HLSReducedStubLayer_z_V_write;

assign ap_return_1 = HLSReducedStubLayer_phi_V_write;

assign ap_return_2 = HLSReducedStubLayer_r_V_write;

assign ap_return_3 = HLSReducedStubLayer_pt_V_write;

assign ap_return_4 = HLSReducedStubLayer_index_V_write;

endmodule //VMRouterDispatcher_AddStub
