-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity VMRouterDispatcher_AddStub is
port (
    HLSReducedStubLayer_z_V_write : IN STD_LOGIC_VECTOR (3 downto 0);
    HLSReducedStubLayer_phi_V_write : IN STD_LOGIC_VECTOR (2 downto 0);
    HLSReducedStubLayer_r_V_write : IN STD_LOGIC_VECTOR (1 downto 0);
    HLSReducedStubLayer_pt_V_write : IN STD_LOGIC_VECTOR (2 downto 0);
    HLSReducedStubLayer_index_V_write : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of VMRouterDispatcher_AddStub is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';



begin



    ap_return_0 <= HLSReducedStubLayer_z_V_write;
    ap_return_1 <= HLSReducedStubLayer_phi_V_write;
    ap_return_2 <= HLSReducedStubLayer_r_V_write;
    ap_return_3 <= HLSReducedStubLayer_pt_V_write;
    ap_return_4 <= HLSReducedStubLayer_index_V_write;
end behav;
