lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH1Z2"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH3Z1"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH3Z2"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH4Z1"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH2Z1"}
lappend pragmaStatus5 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH4Z2"}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH1Z1"}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouter.cpp" location "VMRouterDispatcher" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'VMRouterDispatcher' does not exist in any synthesis source file." variable "nPH2Z2"}
lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH1Z2"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH3Z1"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH3Z2"}
lappend pragmaStatus3 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH4Z1"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH2Z1"}
lappend pragmaStatus5 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH4Z2"}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH1Z1"}
lappend pragmaStatus7 {pragma "ARRAY_PARTITION" source "/mnt/scratch/djc448/firmware-hls/project/../TrackletAlgorithm/VMRouterDispatcher.cpp" location "VMRouterDispatcher" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "nPH2Z2"}
